### ISSUE TITLE
每次使用牛子时回复中都会携带 "牛子修炼结束，你感觉......"

### ISSUE THREAD

**Issue by tkgs0** [opq-osc/chinchin-pk#5]
chinchin-pk 版本: 2.5.0
Python 版本: 3.10.8
系统版本: Debian 11

当牛子修炼完成后, 每次使用牛子时回复中都会携带 `牛子修炼结束，你感觉前所未有的舒服，增加了XX厘米`, 
控制台无警告, 无报错

以下是发生问题的聊天截图:
![IMG_20230218_083433](https://user-images.githubusercontent.com/107618388/219822161-2d2252b5-9c11-49f7-914c-628ec2686bf4.png)

期望行为: `牛子修炼结束` 提示一次即可

实际行为: `牛子修炼结束` 的提示在每一次回复中都出现

**Comment by fz6m** [comment]
e2e 测试是通过的：

https://github.com/opq-osc/chinchin-pk/blob/e27448e0252573d5cc95511d302c681e65640abe/test.py#L402-L465

结果只提示一次：

https://github.com/opq-osc/chinchin-pk/blob/e27448e0252573d5cc95511d302c681e65640abe/__snapshot__/--farm/snapshot-1676547755.txt#L43-L55

新版本在群里是正常运行的，检查下你 fork 部分的逻辑吧。

**Comment by fz6m** [comment]
如果每次同步上游比较复杂的话，欢迎 PR 增加扩展方法，尽量保证每次新版本使用的 `src` 是一个没有改动的整体。

**Comment by tkgs0** [comment]
感谢作者回复, 我再检查一下我这边的代码
