### ISSUE TITLE
[Bug] 成就查询问题

### ISSUE THREAD

**Issue by fz6m** [opq-osc/chinchin-pk#8]
在某个群组内发现成就查询有问题。

因 e2e 测试通过，暂时原因不明。

**Comment by Lancercmd** [comment]
是指当一个用户同时有两个成就时，之后的每一次指令都会循环获得成就？

**Comment by fz6m** [comment]
复现不了：

https://github.com/opq-osc/chinchin-pk/blob/11be7fe231aa9510c1790814368759dad5376e25/__snapshot__/--issue-8/snapshot-1677388137.txt#L12-L26

应该还有其他条件。

**Comment by Lancercmd** [comment]
我试了下确实就是这样，如果在已有一个成就的情况下，下一次用指令又获得一个成就，那么就会替代掉之前的成就。然后就变成每一次指令循环获得另一个成就。只要从 db 擦除对应人的 badge_ids 让其使用任一可触发成就查询的操作，那么久能同时获取两个成就，并且之后不会再出现反复获得成就。
